version: "3.9"
services:
  api:
    image: "python:slim"
    volumes:
      - ./api:/code/api
    working_dir: /code/api
    entrypoint: ./run.sh
    ports:
      - 50:5000
  nfc:
    image: "python:slim" # TODO: check image
    volumes:
      - ./nfc:/code/nfc
      - ./files:/code/files
    working_dir: /code/nfc
    entrypoint: ./run.sh
    ports:
      - 80:8000